# Generated by Django 3.2.9 on 2021-12-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('departmentName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('facultyID', models.IntegerField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50)),
                ('departmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Room_T',
            fields=[
                ('roomID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('roomSize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolTitle', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='SchoolTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t'),
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('creditHour', models.IntegerField()),
                ('departmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNo', models.IntegerField()),
                ('capacity', models.IntegerField(null=True)),
                ('enrolled', models.IntegerField(null=True)),
                ('blocked', models.CharField(max_length=3, null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('day', models.CharField(max_length=10, null=True)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('maxSize', models.IntegerField(null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t')),
                ('facultyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.faculty_t')),
                ('roomID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.room_t')),
            ],
            options={
                'unique_together': {('courseID', 'sectionNo', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Prerequisite_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereqID', models.CharField(max_length=7, null=True)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OfferedCourseID', to='seasapp.course_t')),
            ],
            options={
                'unique_together': {('courseID', 'prereqID')},
            },
        ),
    ]
