# Generated by Django 3.2.9 on 2021-12-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolTitle', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('departmentName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('schoolTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t')),
            ],
        ),
    ]
