# Generated by Django 3.2.9 on 2021-12-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0002_modelwithfilefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department_t',
            old_name='SchoolTitle',
            new_name='schoolTitle',
        ),
    ]
