# Generated by Django 3.2.9 on 2021-12-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0002_department_t_school_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=120)),
                ('creditHour', models.IntegerField(null=True)),
                ('departmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
                ('schoolTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('facultyID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50)),
                ('departmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Room_T',
            fields=[
                ('roomID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('roomSize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNo', models.IntegerField()),
                ('capacity', models.IntegerField(null=True)),
                ('enrolled', models.IntegerField(null=True)),
                ('blocked', models.CharField(max_length=3, null=True)),
                ('startTime', models.CharField(max_length=10, null=True)),
                ('endTime', models.CharField(max_length=10, null=True)),
                ('day', models.CharField(max_length=8, null=True)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t')),
                ('facultyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.faculty_t')),
                ('roomID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.room_t')),
            ],
        ),
        migrations.AddConstraint(
            model_name='section_t',
            constraint=models.UniqueConstraint(fields=('courseID', 'sectionNo', 'semester', 'year'), name='Unique'),
        ),
    ]
