# Generated by Django 3.2.9 on 2021-12-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0003_rename_schooltitle_department_t_schooltitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOfferedCourse_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coofferredwith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coofferredwith', to='seasapp.course_t')),
                ('offeredCourseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OfferedCourseID', to='seasapp.course_t')),
            ],
            options={
                'unique_together': {('offeredCourseID', 'coofferredwith')},
            },
        ),
        migrations.DeleteModel(
            name='Prerequisite_T',
        ),
    ]
