# Generated by Django 3.2.9 on 2021-12-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0004_auto_20211208_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_t',
            name='schoolTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t'),
        ),
    ]
