# Generated by Django 3.2.9 on 2021-12-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0005_course_t_schooltitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_t',
            name='maxSize',
        ),
    ]
