# Generated by Django 3.2.9 on 2021-12-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0006_remove_section_t_maxsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t'),
        ),
    ]
