# Generated by Django 3.2.9 on 2021-12-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0007_alter_section_t_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coofferedcourse_t',
            name='coofferredwith',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OfferedCourseID', to='seasapp.course_t'), max_length=50),
        ),
    ]
