# Generated by Django 3.2.9 on 2021-12-10 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0008_alter_coofferedcourse_t_coofferredwith'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_t',
            old_name='courseID',
            new_name='offeredCourseID',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='courseID',
            new_name='offeredCourseID',
        ),
        migrations.AlterField(
            model_name='coofferedcourse_t',
            name='coofferredwith',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t'), max_length=50),
        ),
        migrations.AlterField(
            model_name='coofferedcourse_t',
            name='offeredCourseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t'),
        ),
        migrations.AlterUniqueTogether(
            name='section_t',
            unique_together={('offeredCourseID', 'sectionNo', 'semester', 'year')},
        ),
    ]
