# Generated by Django 3.2.9 on 2021-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0009_auto_20211210_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_t',
            name='facultyID',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
