# Generated by Django 3.2.9 on 2021-12-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0010_alter_faculty_t_facultyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_t',
            name='schoolTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t'),
        ),
        migrations.AlterField(
            model_name='faculty_t',
            name='facultyID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
