# Generated by Django 3.2.9 on 2021-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0011_auto_20211212_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='endTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section_t',
            name='startTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
