# Generated by Django 3.2.9 on 2021-12-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0012_auto_20211212_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_t',
            old_name='offeredCourseID',
            new_name='courseID',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='offeredCourseID',
            new_name='courseID',
        ),
        migrations.AlterUniqueTogether(
            name='section_t',
            unique_together={('courseID', 'sectionNo', 'semester', 'year')},
        ),
        migrations.DeleteModel(
            name='CoOfferedCourse_T',
        ),
    ]
