# Generated by Django 3.2.9 on 2021-12-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0013_auto_20211221_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCourse_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t')),
            ],
        ),
    ]
