# Generated by Django 3.2.9 on 2021-12-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0014_offeredcourse_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredcourse_t',
            name='offerredwith',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offeredwith', to='seasapp.course_t'),
        ),
        migrations.AlterField(
            model_name='offeredcourse_t',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to='seasapp.course_t'),
        ),
        migrations.AlterUniqueTogether(
            name='offeredcourse_t',
            unique_together={('courseID', 'offerredwith')},
        ),
    ]
