# Generated by Django 3.2.9 on 2021-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0015_auto_20211221_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeredcourse_t',
            old_name='offerredwith',
            new_name='offeredWith',
        ),
        migrations.AlterField(
            model_name='school_t',
            name='schoolTitle',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='offeredcourse_t',
            unique_together={('courseID', 'offeredWith')},
        ),
    ]
