# Generated by Django 3.2.9 on 2021-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0016_auto_20211221_2223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeredcourse_t',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='offeredcourse_t',
            constraint=models.UniqueConstraint(fields=('courseID', 'offeredWith'), name='unique'),
        ),
    ]
