# Generated by Django 3.2.9 on 2021-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0017_auto_20211221_2230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section_t',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='section_t',
            constraint=models.UniqueConstraint(fields=('courseID', 'sectionNo', 'semester', 'year'), name='Unique'),
        ),
    ]
