# Generated by Django 3.2.9 on 2021-12-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0018_auto_20211221_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredcourse_t',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='seasapp.course_t'),
        ),
    ]
