# Generated by Django 3.2.9 on 2021-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0019_alter_offeredcourse_t_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_t',
            name='creditHour',
            field=models.IntegerField(null=True),
        ),
    ]
